
import { MorningTopic, AfternoonTopic } from './types';

export const SESSION_COLORS = {
  morning: 'bg-blue-500',
  afternoon: 'bg-orange-500',
  morningText: 'text-blue-500',
  afternoonText: 'text-orange-500',
  morningBorder: 'border-blue-500',
  afternoonBorder: 'border-orange-500',
};

export const TOPIC_NAMES: { [key in MorningTopic | AfternoonTopic]: { ja: string, en: string } } = {
  // Morning
  foundations: { ja: '基礎理論', en: 'Foundations' },
  architecture: { ja: 'コンピュータ構成要素', en: 'Architecture' },
  network: { ja: 'ネットワーク', en: 'Network' },
  security: { ja: 'セキュリティ', en: 'Security' },
  database: { ja: 'データベース', en: 'Database' },
  management: { ja: 'プロジェクトマネジメント', en: 'Management' },
  strategy: { ja: '経営戦略', en: 'Strategy' },
  // Afternoon
  programming: { ja: 'プログラミング', en: 'Programming' },
  design: { ja: 'ソフトウェア設計', en: 'Software Design' },
  // Re-using morning topics where applicable
};

export const translations = {
  ja: {
    home: 'ホーム',
    study: '学習',
    calendar: 'カレンダー',
    status: 'ステータス',
    welcome: 'FE試験 AIコーチへようこそ',
    todays_task: '今日のタスク',
    start_morning_session: '午前問題を始める',
    start_afternoon_session: '午後問題を始める',
    overall_progress: '全体の進捗',
    morning_session: '午前',
    afternoon_session: '午後',
    select_study_mode: '学習モードを選択',
    quick_quiz: 'クイッククイズ (5問)',
    topic_quiz: '分野別クイズ',
    mock_exam: '模試',
    select_topic: '分野を選択してください',
    start_quiz: 'クイズ開始',
    study_history: '学習履歴',
    no_history: '学習履歴はまだありません。',
    my_status: '学習ステータス',
    weak_areas: '苦手分野',
    strong_areas: '得意分野',
    pass_probability: '合格確率予測',
    get_prediction: 'AIに合格確率を予測してもらう',
    predicting: '予測中...',
    review_mistakes: '間違えた問題を復習',
    no_mistakes: '間違えた問題はありません。素晴らしい！',
    question: '問題',
    submit: '回答する',
    next: '次へ',
    correct: '正解！',
    incorrect: '不正解',
    explanation: '解説',
    correct_answer_is: '正解は: {{answer}}',
    quiz_results: 'クイズ結果',
    score: 'スコア',
    back_to_study_menu: '学習メニューに戻る',
    language: '言語',
    english: 'English',
    japanese: '日本語',
    ...Object.fromEntries(Object.entries(TOPIC_NAMES).map(([key, value]) => [key, value.ja]))
  },
  en: {
    home: 'Home',
    study: 'Study',
    calendar: 'Calendar',
    status: 'Status',
    welcome: 'Welcome to FE Exam AI Coach',
    todays_task: "Today's Task",
    start_morning_session: 'Start Morning Session',
    start_afternoon_session: 'Start Afternoon Session',
    overall_progress: 'Overall Progress',
    morning_session: 'Morning',
    afternoon_session: 'Afternoon',
    select_study_mode: 'Select Study Mode',
    quick_quiz: 'Quick Quiz (5 questions)',
    topic_quiz: 'Quiz by Topic',
    mock_exam: 'Mock Exam',
    select_topic: 'Please select a topic',
    start_quiz: 'Start Quiz',
    study_history: 'Study History',
    no_history: 'No study history yet.',
    my_status: 'My Status',
    weak_areas: 'Weak Areas',
    strong_areas: 'Strong Areas',
    pass_probability: 'Pass Probability Forecast',
    get_prediction: 'Get AI Pass Probability Forecast',
    predicting: 'Predicting...',
    review_mistakes: 'Review Mistakes',
    no_mistakes: 'No mistaken questions. Great job!',
    question: 'Question',
    submit: 'Submit',
    next: 'Next',
    correct: 'Correct!',
    incorrect: 'Incorrect',
    explanation: 'Explanation',
    correct_answer_is: 'The correct answer is: {{answer}}',
    quiz_results: 'Quiz Results',
    score: 'Score',
    back_to_study_menu: 'Back to Study Menu',
    language: 'Language',
    english: 'English',
    japanese: 'Japanese',
    ...Object.fromEntries(Object.entries(TOPIC_NAMES).map(([key, value]) => [key, value.en]))
  }
};
